import React from "react";
import ModalFooter from "./ModalFooter";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ModalFooter,
  "https://www.figma.com/design/fawuW3w9DKApoSce9VRO5R/Joystick-Design-System?node-id=4261%3A255",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showSecondaryButton": figma.boolean('Show secondary button'),
      // "showTertiaryButton": figma.boolean('Show tertiary button')
    },
    example: (props) => <ModalFooter />,
  },
);
