import React from "react";
import ModalHeader from "./ModalHeader";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ModalHeader,
  "https://www.figma.com/design/fawuW3w9DKApoSce9VRO5R/Joystick-Design-System?node-id=9228%3A1898",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showIcon": figma.boolean('Show Icon'),
      // "title": figma.string('Title'),
      // "dissmissable": figma.boolean('Dissmissable'),
      // "showTitle": figma.boolean('Show title'),
      // "type": figma.enum('Type', {
      //   "Default": "default",
      //   "Image (v2)": "image--v2-"
      // })
    },
    example: (props) => <ModalHeader />,
  },
);
